drivers/argos: Update Argos driver to Oct 30th 2020
- mmap_lock.h previously used mmap_sem struct field
- this was removed inbetween 5.4 and 5.10:
./include/linux/mmap_lock.h:8:16: error: 'struct mm_struct' has no member named 'mmap_sem'
- transition to using new mmap_lock struct field

TESTED=Tested 5.10 in session d42c369dc0977928:
> uname -r
...5.10...
> dmesg | grep "vargos"
...
Loading VArgos driver: ffbdb006109d.
...
"


Change-Id: I5f8a964b3a29373c1d4c1ac6e083010a85b9474a
(cherry picked from commit 3593f92bb3f903c5790096d7cc7db1b2fe8a4baf)